const langObj = [
  {code:"ab",name:"Abkhaz",nativeName:"аҧсуа", value: "abkhaz"},
  {code:"aa",name:"Afar",nativeName:"Afaraf", value: "afar"},
  {code:"af",name:"Afrikaans",nativeName:"Afrikaans", value: "afrikaans"},
  {code:"ak",name:"Akan",nativeName:"Akan", value: "akan"},
  {code:"sq",name:"Albanian",nativeName:"Shqip", value: "albanian"},
  {code:"am",name:"Amharic",nativeName:"አማርኛ", value: "amharic"},
  {code:"ar",name:"Arabic",nativeName:"العربية", value: "arabic"},
  {code:"an",name:"Aragonese",nativeName:"Aragonés", value: "aragonese"},
  {code:"hy",name:"Armenian",nativeName:"Հայերեն", value: "armenian"},
  {code:"as",name:"Assamese",nativeName:"অসমীয়া", value: "assamese"},
  {code:"av",name:"Avaric",nativeName:"авар мацӀ, магӀарул мацӀ", value: "avaric"},
  {code:"ae",name:"Avestan",nativeName:"avesta", value: "avestan"},
  {code:"ay",name:"Aymara",nativeName:"aymar aru", value: "aymara"},
  {code:"az",name:"Azerbaijani",nativeName:"azərbaycan dili", value: "azerbaijani"},
  {code:"bm",name:"Bambara",nativeName:"bamanankan", value: "bambara"},
  {code:"ba",name:"Bashkir",nativeName:"башҡорт теле", value: "bashkir"},
  {code:"eu",name:"Basque",nativeName:"euskara, euskera", value: "basque"},
  {code:"be",name:"Belarusian",nativeName:"Беларуская", value: "belarusian"},
  {code:"bn",name:"Bengali",nativeName:"বাংলা", value: "bengali"},
  {code:"bh",name:"Bihari",nativeName:"भोजपुरी", value: "bihari"},
  {code:"bi",name:"Bislama",nativeName:"Bislama", value: "bislama"},
  {code:"bs",name:"Bosnian",nativeName:"bosanski jezik", value: "bosnian"},
  {code:"br",name:"Breton",nativeName:"brezhoneg", value: "breton"},
  {code:"bg",name:"Bulgarian",nativeName:"български език", value: "bulgarian"},
  {code:"my",name:"Burmese",nativeName:"ဗမာစာ", value: "burmese"},
  {code:"ca",name:"Catalan; Valencian",nativeName:"Català", value: "catalan"},
  {code:"ch",name:"Chamorro",nativeName:"Chamoru", value: "chamorro"},
  {code:"ce",name:"Chechen",nativeName:"нохчийн мотт", value: "chechen"},
  {code:"ny",name:"Chichewa; Chewa; Nyanja",nativeName:"chiCheŵa, chinyanja", value: "chichewa"},
  {code:"zh",name:"Chinese",nativeName:"中文 (Zhōngwén), 汉语, 漢語", value: "chinese"},
  {code:"cv",name:"Chuvash",nativeName:"чӑваш чӗлхи", value: "chuvash"},
  {code:"kw",name:"Cornish",nativeName:"Kernewek", value: "cornish"},
  {code:"co",name:"Corsican",nativeName:"corsu, lingua corsa", value: "corsican"},
  {code:"cr",name:"Cree",nativeName:"ᓀᐦᐃᔭᐍᐏᐣ", value: "cree"},
  {code:"hr",name:"Croatian",nativeName:"hrvatski", value: "croatian"},
  {code:"cs",name:"Czech",nativeName:"česky, čeština", value: "czech"},
  {code:"da",name:"Danish",nativeName:"dansk", value: "danish"},
  {code:"dv",name:"Divehi; Dhivehi; Maldivian;",nativeName:"ދިވެހި", value: "divehi"},
  {code:"nl",name:"Dutch",nativeName:"Nederlands, Vlaams", value: "dutch"},
  {code:"en",name:"English",nativeName:"English", value: "english"},
  {code:"eo",name:"Esperanto",nativeName:"Esperanto", value: "esperanto"},
  {code:"et",name:"Estonian",nativeName:"eesti, eesti keel", value: "estonian"},
  {code:"ee",name:"Ewe",nativeName:"Eʋegbe", value: "ewe"},
  {code:"fo",name:"Faroese",nativeName:"føroyskt", value: "faroese"},
  {code:"fj",name:"Fijian",nativeName:"vosa Vakaviti", value: "fijian"},
  {code:"fi",name:"Finnish",nativeName:"suomi, suomen kieli", value: "finnish"},
  {code:"fr",name:"French",nativeName:"français, langue française", value: "french"},
  {code:"ff",name:"Fula; Fulah; Pulaar; Pular",nativeName:"Fulfulde, Pulaar, Pular", value: "fula"},
  {code:"gl",name:"Galician",nativeName:"Galego", value: "galician"},
  {code:"ka",name:"Georgian",nativeName:"ქართული", value: "georgian"},
  {code:"de",name:"German",nativeName:"Deutsch", value: "german"},
  {code:"el",name:"Greek, Modern",nativeName:"Ελληνικά", value: "greek"},
  {code:"gn",name:"Guaraní",nativeName:"Avañeẽ", value: "guaraní"},
  {code:"gu",name:"Gujarati",nativeName:"ગુજરાતી", value: "gujarati"},
  {code:"ht",name:"Haitian; Haitian Creole",nativeName:"Kreyòl ayisyen", value: "haitian"},
  {code:"ha",name:"Hausa",nativeName:"Hausa, هَوُسَ", value: "hausa"},
  {code:"he",name:"Hebrew (modern)",nativeName:"עברית", value: "hebrew"},
  {code:"hz",name:"Herero",nativeName:"Otjiherero", value: "herero"},
  {code:"hi",name:"Hindi",nativeName:"हिन्दी, हिंदी", value: "hindi"},
  {code:"ho",name:"Hiri Motu",nativeName:"Hiri Motu", value: "hiri"},
  {code:"hu",name:"Hungarian",nativeName:"Magyar", value: "hungarian"},
  {code:"ia",name:"Interlingua",nativeName:"Interlingua", value: "interlingua"},
  {code:"id",name:"Indonesian",nativeName:"Bahasa Indonesia", value: "indonesian"},
  {code:"ga",name:"Irish",nativeName:"Gaeilge", value: "irish"},
  {code:"ig",name:"Igbo",nativeName:"Asụsụ Igbo", value: "igbo"},
  {code:"ik",name:"Inupiaq",nativeName:"Iñupiaq, Iñupiatun", value: "inupiaq"},
  {code:"io",name:"Ido",nativeName:"Ido", value: "ido"},
  {code:"is",name:"Icelandic",nativeName:"Íslenska", value: "icelandic"},
  {code:"it",name:"Italian",nativeName:"Italiano", value: "italian"},
  {code:"iu",name:"Inuktitut",nativeName:"ᐃᓄᒃᑎᑐᑦ", value: "inuktitut"},
  {code:"ja",name:"Japanese",nativeName:"日本語 (にほんご／にっぽんご)", value: "japanese"},
  {code:"jv",name:"Javanese",nativeName:"basa Jawa", value: "javanese"},
  {code:"kl",name:"Kalaallisut, Greenlandic",nativeName:"kalaallisut", value: "kalaallisut"},
  {code:"kn",name:"Kannada",nativeName:"ಕನ್ನಡ", value: "kannada"},
  {code:"kr",name:"Kanuri",nativeName:"Kanuri", value: "kanuri"},
  {code:"ks",name:"Kashmiri",nativeName:"कश्मीरी, كشميري‎", value: "kashmiri"},
  {code:"kk",name:"Kazakh",nativeName:"Қазақ тілі", value: "kazakh"},
  {code:"km",name:"Khmer",nativeName:"ភាសាខ្មែរ", value: "khmer"},
  {code:"ki",name:"Kikuyu, Gikuyu",nativeName:"Gĩkũyũ", value: "kikuyu"},
  {code:"rw",name:"Kinyarwanda",nativeName:"Ikinyarwanda", value: "kinyarwanda"},
  {code:"ky",name:"Kirghiz, Kyrgyz",nativeName:"кыргыз тили", value: "kirghiz"},
  {code:"kv",name:"Komi",nativeName:"коми кыв", value: "komi"},
  {code:"kg",name:"Kongo",nativeName:"KiKongo", value: "kongo"},
  {code:"ko",name:"Korean",nativeName:"한국어 (韓國語), 조선말 (朝鮮語)", value: "korean"},
  {code:"ku",name:"Kurdish",nativeName:"Kurdî, كوردی‎", value: "kurdish"},
  {code:"kj",name:"Kwanyama, Kuanyama",nativeName:"Kuanyama", value: "kwanyama"},
  {code:"la",name:"Latin",nativeName:"latine, lingua latina", value: "latin"},
  {code:"lb",name:"Luxembourgish, Letzeburgesch",nativeName:"Lëtzebuergesch", value: "luxembourgish"},
  {code:"lg",name:"Luganda",nativeName:"Luganda", value: "luganda"},
  {code:"li",name:"Limburgish, Limburgan, Limburger",nativeName:"Limburgs", value: "limburgish"},
  {code:"ln",name:"Lingala",nativeName:"Lingála", value: "lingala"},
  {code:"lo",name:"Lao",nativeName:"ພາສາລາວ", value: "lao"},
  {code:"lt",name:"Lithuanian",nativeName:"lietuvių kalba", value: "lithuanian"},
  {code:"lu",name:"Luba-Katanga",nativeName:"", value: "luba"},
  {code:"lv",name:"Latvian",nativeName:"latviešu valoda", value: "latvian"},
  {code:"gv",name:"Manx",nativeName:"Gaelg, Gailck", value: "manx"},
  {code:"mk",name:"Macedonian",nativeName:"македонски јазик", value: "macedonian"},
  {code:"mg",name:"Malagasy",nativeName:"Malagasy fiteny", value: "malagasy"},
  {code:"ms",name:"Malay",nativeName:"bahasa Melayu, بهاس ملايو‎", value: "malay"},
  {code:"ml",name:"Malayalam",nativeName:"മലയാളം", value: "malayalam"},
  {code:"mt",name:"Maltese",nativeName:"Malti", value: "maltese"},
  {code:"mi",name:"Māori",nativeName:"te reo Māori", value: "māori"},
  {code:"mr",name:"Marathi (Marāṭhī)",nativeName:"मराठी", value: "marathi"},
  {code:"mh",name:"Marshallese",nativeName:"Kajin M̧ajeļ", value: "marshallese"},
  {code:"mn",name:"Mongolian",nativeName:"монгол", value: "mongolian"},
  {code:"na",name:"Nauru",nativeName:"Ekakairũ Naoero", value: "nauru"},
  {code:"nv",name:"Navajo, Navaho",nativeName:"Diné bizaad, Dinékʼehǰí", value: "navajo"},
  {code:"nb",name:"Norwegian Bokmål",nativeName:"Norsk bokmål", value: "norwegian"},
  {code:"nd",name:"North Ndebele",nativeName:"isiNdebele", value: "north ndebele"},
  {code:"ne",name:"Nepali",nativeName:"नेपाली", value: "nepali"},
  {code:"ng",name:"Ndonga",nativeName:"Owambo", value: "ndonga"},
  {code:"nn",name:"Norwegian Nynorsk",nativeName:"Norsk nynorsk", value: "norwegian nynorsk"},
  {code:"no",name:"Norwegian",nativeName:"Norsk", value: "norwegian"},
  {code:"ii",name:"Nuosu",nativeName:"ꆈꌠ꒿ Nuosuhxop", value: "nuosu"},
  {code:"nr",name:"South Ndebele",nativeName:"isiNdebele", value: "south ndebele"},
  {code:"oc",name:"Occitan",nativeName:"Occitan", value: "occitan"},
  {code:"oj",name:"Ojibwe, Ojibwa",nativeName:"ᐊᓂᔑᓈᐯᒧᐎᓐ", value: "ojibwe"},
  {code:"om",name:"Oromo",nativeName:"Afaan Oromoo", value: "oromo"},
  {code:"or",name:"Oriya",nativeName:"ଓଡ଼ିଆ", value: "oriya"},
  {code:"os",name:"Ossetian, Ossetic",nativeName:"ирон æвзаг", value: "ossetian"},
  {code:"pa",name:"Panjabi, Punjabi",nativeName:"ਪੰਜਾਬੀ, پنجابی‎", value: "panjabi"},
  {code:"pi",name:"Pāli",nativeName:"पाऴि", value: "pāli"},
  {code:"fa",name:"Persian",nativeName:"فارسی", value: "persian"},
  {code:"pl",name:"Polish",nativeName:"polski", value: "polish"},
  {code:"ps",name:"Pashto, Pushto",nativeName:"پښتو", value: "pashto"},
  {code:"pt",name:"Portuguese",nativeName:"Português", value: "portuguese"},
  {code:"qu",name:"Quechua",nativeName:"Runa Simi, Kichwa", value: "quechua"},
  {code:"rm",name:"Romansh",nativeName:"rumantsch grischun", value: "romansh"},
  {code:"rn",name:"Kirundi",nativeName:"kiRundi", value: "kirundi"},
  {code:"ro",name:"Romanian, Moldavian, Moldovan",nativeName:"română", value: "romanian"},
  {code:"ru",name:"Russian",nativeName:"русский язык", value: "russian"},
  {code:"sa",name:"Sanskrit (Saṁskṛta)",nativeName:"संस्कृतम्", value: "sanskrit"},
  {code:"sc",name:"Sardinian",nativeName:"sardu", value: "sardinian"},
  {code:"sd",name:"Sindhi",nativeName:"सिन्धी, سنڌي، سندھی‎", value: "sindhi"},
  {code:"se",name:"Northern Sami",nativeName:"Davvisámegiella", value: "sorthern sami"},
  {code:"sm",name:"Samoan",nativeName:"gagana faa Samoa", value: "samoan"},
  {code:"sg",name:"Sango",nativeName:"yângâ tî sängö", value: "sango"},
  {code:"sr",name:"Serbian",nativeName:"српски језик", value: "serbian"},
  {code:"gd",name:"Scottish Gaelic; Gaelic",nativeName:"Gàidhlig", value: "scottish"},
  {code:"sn",name:"Shona",nativeName:"chiShona", value: "shona"},
  {code:"si",name:"Sinhala, Sinhalese",nativeName:"සිංහල", value: "sinhala"},
  {code:"sk",name:"Slovak",nativeName:"slovenčina", value: "slovak"},
  {code:"sl",name:"Slovene",nativeName:"slovenščina", value: "slovene"},
  {code:"so",name:"Somali",nativeName:"Soomaaliga, af Soomaali", value: "somali"},
  {code:"st",name:"Southern Sotho",nativeName:"Sesotho", value: "southern sotho"},
  {code:"es",name:"Spanish",nativeName:"español, castellano", value: "spanish"},
  {code:"su",name:"Sundanese",nativeName:"Basa Sunda", value: "sundanese"},
  {code:"sw",name:"Swahili",nativeName:"Kiswahili", value: "swahili"},
  {code:"ss",name:"Swati",nativeName:"SiSwati", value: "swati"},
  {code:"sv",name:"Swedish",nativeName:"svenska", value: "swedish"},
  {code:"ta",name:"Tamil",nativeName:"தமிழ்", value: "tamil"},
  {code:"te",name:"Telugu",nativeName:"తెలుగు", value: "telugu"},
  {code:"tg",name:"Tajik",nativeName:"тоҷикӣ, toğikī, تاجیکی‎", value: "tajik"},
  {code:"th",name:"Thai",nativeName:"ไทย", value: "thai"},
  {code:"ti",name:"Tigrinya",nativeName:"ትግርኛ", value: "tigrinya"},
  {code:"bo",name:"Tibetan Standard, Tibetan, Central",nativeName:"བོད་ཡིག", value: "tibetan"},
  {code:"tk",name:"Turkmen",nativeName:"Türkmen, Түркмен", value: "turkmen"},
  {code:"tl",name:"Tagalog",nativeName:"Wikang Tagalog", value: "tagalog"},
  {code:"tn",name:"Tswana",nativeName:"Setswana", value: "tswana"},
  {code:"to",name:"Tonga (Tonga Islands)",nativeName:"faka Tonga", value: "tonga"},
  {code:"tr",name:"Turkish",nativeName:"Türkçe", value: "turkish"},
  {code:"ts",name:"Tsonga",nativeName:"Xitsonga", value: "tsonga"},
  {code:"tt",name:"Tatar",nativeName:"татарча, tatarça, تاتارچا‎", value: "tatar"},
  {code:"tw",name:"Twi",nativeName:"Twi", value: "twi"},
  {code:"ty",name:"Tahitian",nativeName:"Reo Tahiti", value: "tahitian"},
  {code:"ug",name:"Uighur, Uyghur",nativeName:"Uyƣurqə, ئۇيغۇرچە‎", value: "uighur"},
  {code:"uk",name:"Ukrainian",nativeName:"українська", value: "ukrainian"},
  {code:"ur",name:"Urdu",nativeName:"اردو", value: "urdu"},
  {code:"uz",name:"Uzbek",nativeName:"zbek, Ўзбек, أۇزبېك‎", value: "uzbek"},
  {code:"ve",name:"Venda",nativeName:"Tshivenḓa", value: "venda"},
  {code:"vi",name:"Vietnamese",nativeName:"Tiếng Việt", value: "vietnamese"},
  {code:"vo",name:"Volapük",nativeName:"Volapük", value: "volapük"},
  {code:"wa",name:"Walloon",nativeName:"Walon", value: "walloon"},
  {code:"cy",name:"Welsh",nativeName:"Cymraeg", value: "welsh"},
  {code:"wo",name:"Wolof",nativeName:"Wollof", value: "wolof"},
  {code:"fy",name:"Western Frisian",nativeName:"Frysk", value: "western"},
  {code:"xh",name:"Xhosa",nativeName:"isiXhosa", value: "xhosa"},
  {code:"yi",name:"Yiddish",nativeName:"ייִדיש", value: "yiddish"},
  {code:"yo",name:"Yoruba",nativeName:"Yorùbá", value: "yoruba"},
  {code:"za",name:"Zhuang, Chuang",nativeName:"Saɯ cueŋƅ, Saw cuengh", value: "zhuang"}
];
